package movieapp.persistence.repository;

import java.util.stream.Stream;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import movieapp.dto.MovieStatistics;
import movieapp.persistence.entity.Movie;

// paramètres de généricité :
//	T = Movie : objets gérés par le répository
//	ID= Integer : type de la clé primaire
// By Default use database in Memory H2
//
// Query auto generated by Spring according to following rules:
// https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation
public interface MovieRepository extends JpaRepository<Movie, Integer>{
	// gifts : save/findAll/findById/...
	
	// select movie0_.id as id1_0_, movie0_.duration as duration2_0_, movie0_.title as title3_0_, movie0_.year as year4_0_ 
	// from movie movie0_ 
	// where movie0_.title=?
	Stream<Movie> findByTitle(String title);
		
	// global statistics with DTO object
	@Query("select new movieapp.dto.MovieStatistics("
			+ "COUNT(*), MIN(m.year), MAX(m.year), "
			+ "COALESCE(SUM(duration),0), "
			+ "AVG(duration), MIN(duration), MAX(duration), "
			+ "MIN(LENGTH(title)), MAX(LENGTH(title))) "
			+ "from Movie m")
	MovieStatistics statisticsDto();
	
}
